FROM python:3.11-slim-bookworm
WORKDIR /usr/src/app
COPY back_end/requirements.txt ./
RUN pip install --no-cache-dir torch==2.2.2 torchvision==0.17.2
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]